DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS board;
DROP TABLE IF EXISTS list;
DROP TABLE IF EXISTS task;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	token TEXT 
);

CREATE TABLE board (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	color TEXT DEFAULT '#FFF',
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE list (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	sort INTEGER DEFAULT 0,
	board_id INTEGER NOT NULL,
	FOREIGN KEY (board_id) REFERENCES board (id)
);

CREATE TABLE task (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	task TEXT NOT NULL,
	decription TEXT NOT NULL,
	list_id INTEGER NOT NULL,
	color TEXT DEFAULT '#FFF',
	FOREIGN KEY (list_id) REFERENCES list (id)
);